[package]
name = "key-stream"
description = "A library for async key streaming."
authors = ["Artsiom Kaltovich <kaltovichartyom@gmail.com>"]
version = "0.10.0"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/artsiomkaltovich/key-stream"

[features]
default = []
bench-variants = []

[dependencies]
futures = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["sync", "rt"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "time"] }
futures = { version = "0.3", features = ["alloc"] }
criterion = { version = "0.8", features = ["async_tokio"] }

[[bench]]
name = "key_stream"
harness = false
